@startuml
'https://plantuml.com/class-diagram
class Controller {

}


class InventoryApplication {
 + main(String[] args) : void
 + start(Stage primaryStage) : void
}

class InventoryEditor {

}

class InventoryList {

}

class Item {

}

class Search {

}

class Validator {

}

class SceneMaker {

}

class Sorter {

}

javafx.Application <|-- InventoryApplication
Controller -- InventoryApplication
Controller *-- "uses"Search
Controller *-- "uses"InventoryEditor
Controller *-- "uses"SceneMaker
Controller"1" --* "contains"InventoryList
InventoryList "100..*"--* "contains" Item
InventoryEditor *-- "uses" Validator
Controller *-- "uses"Sorter
@enduml